baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Danny's Wiki"
theme = "hugo-book"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
BookTheme = 'auto'
BookLogo = 'wikipedia.svg'
BookToC = true
BookRepo = 'https://github.com/Capybaric123/Danny-s-Wiki/tree/main'
BookEditPath = 'tree/main/content'
BookSearch = true
BookComments = true