baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Danny's Wiki"
theme = "hugo-book"

disablePathToLower = true
enableGitInfo = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
BookTheme = 'auto'
BookLogo = 'wikipedia.svg'
BookToC = true
BookRepo = 'https://github.com/Capybaric123/Danny-s-Wiki'
BookEditPath = 'tree/main/'
BookSearch = true
BookComments = true
BookDateFormat = 'January 2, 2006'
